apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbooks-books-pv
  namespace: media
spec:
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /shares/books
    server: ${NAS_IP}
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbooks-books-pvc
  namespace: media
spec:
  storageClassName: ""
  volumeName: openbooks-books-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
