# https://longhorn.io/docs/1.5.1/advanced-resources/deploy/customizing-default-settings/
# https://github.com/longhorn/longhorn-manager/blob/a77b330ef8024b2f0eeb7d0341d1d3ba5b421e41/types/setting.go
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    # only specify values that deviate from defaults

    # general
    allow-collecting-longhorn-usage-metrics: "false"
    default-data-locality: best-effort
    default-replica-count: "2"
    node-down-pod-deletion-policy: delete-both-statefulset-and-deployment-pod
    node-drain-policy: always-allow
    remove-snapshots-during-filesystem-trim: "true"
    upgrade-checker: "false"

    # snapshot checks
    snapshot-data-integrity: enabled
    snapshot-data-integrity-immediate-check-after-snapshot-creation: "false"
    snapshot-data-integrity-cronjob: "0 0 */2 * *" # every 2 days

    # backup
    backup-target-credential-secret: azure-longhorn-backup-secret
    backup-target: azblob://longhorn@core.windows.net/

    # scheduling
    allow-volume-creation-with-degraded-availability: "false"
    replica-auto-balance: best-effort
