# yaml-language-server: $schema=../../../schemas/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: nginx-external
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: ingress-nginx
      version: 4.7.0
      interval: 1h0m0s
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system

  values:
    nameOverride: nginx-external
    controller:
      extraArgs:
        default-ssl-certificate: cert-manager/domain-wildcard

      image:
        image: ingress-nginx/controller
        registry: registry.k8s.io
        tag: v1.8.0

      ingressClass: nginx-external
      ingressClassByName: true

      ingressClassResource:
        name: nginx-external
        enabled: true
        default: false
        controllerValue: k8s.io/ingress-nginx-external

      metrics:
        port: 10254
        portName: metrics
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus

      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${INGRESS_EXTERNAL_IP}
        externalTrafficPolicy: Local

      watchIngressWithoutClass: false
