---
k3s_become: true
k3s_install_hard_links: true
k3s_server:
  disable:
    - servicelb
    - traefik
k3s_server_manifests_urls:
  # Essential Prometheus Operator CRDs (the rest are installed with the kube-prometheus-stack helm release)
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.66.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
    filename: custom-prometheus-podmonitors.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.66.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
    filename: custom-prometheus-prometheusrules.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.66.0/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
    filename: custom-prometheus-scrapeconfigs.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.66.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
    filename: custom-prometheus-servicemonitors.yaml
  # Other Things
  - url: https://raw.githubusercontent.com/longhorn/longhorn/v1.4.2/deploy/longhorn.yaml
    filename: longhorn.yml
  - url: https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
    filename: metallb-native.yaml
  - url: https://github.com/cert-manager/cert-manager/releases/download/v1.12.2/cert-manager.yaml
    filename: cert-manager.yaml

kube_file: /etc/rancher/k3s/k3s.yaml

# Secrets common to both dev and prod
homelab_domain_name: "{{ lookup('azure_keyvault_secret', 'homelab-domainname', vault_url=kv_url) }}"
weave_gitops_app_clientid: "{{ lookup('azure_keyvault_secret', 'weave-gitops-app-clientid', vault_url=kv_url) }}"
weave_gitops_app_clientsecret: "{{ lookup('azure_keyvault_secret', 'weave-gitops-app-clientsecret', vault_url=kv_url) }}"
