apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  interval: 5m
  chart:
    spec:
      chart: reloader
      version: 0.0.124
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
