# yaml-language-server: $schema=../../../../schemas/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logging-nginx-internal
  namespace: nginx-internal
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: ingress-nginx
      version: 4.8.3
      interval: 1h0m0s
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system

  values:
    nameOverride: logging-nginx-internal
    controller:
      extraArgs:
        default-ssl-certificate: cert-manager/domain-wildcard

      ingressClass: logging-nginx-internal
      ingressClassByName: true

      ingressClassResource:
        name: logging-nginx-internal
        enabled: true
        default: false
        controllerValue: k8s.io/logging-ingress-nginx-internal

      metrics:
        port: 10254
        portName: metrics
        enabled: true
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: prometheus

      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${LOGGING_INGRESS_INTERNAL_IP}
        externalTrafficPolicy: Local

      watchIngressWithoutClass: false
