---
localhost:
  hosts:
    127.0.0.1
  vars:
    ansible_connection: local
    branch: ingress-metallb
    target_path: kubernetes/clusters/develop
    github_token:

k3s_cluster:
  hosts:
    master:
      k3s_control_node: true
      ansible_host: 192.168.0.8
    node1:
      ansible_host: 192.168.0.7
  vars:
    ansible_connection: paramiko # don't need to apt-get sshpass
    ansible_user: colin
    ansible_python_interpreter: /usr/bin/python3
    k3s_registration_address: 192.168.0.8
