---
localhost:
  hosts:
    127.0.0.1
  vars:
    flux_version: 0.38.3
    ansible_connection: local
    branch: main
    target_path: kubernetes/clusters/develop
    kv_url: 'https://chickenwaffles-vault-dev.vault.azure.net/'
    github_token: "{{ lookup('azure_keyvault_secret', 'github-token', vault_url=kv_url) }}"

k3s_cluster:
  hosts:
    master:
      k3s_control_node: true
      ansible_host: 192.168.0.8
    node1:
      ansible_host: 192.168.0.7
  vars:
    k3s_release_version: v1.25.6+k3s1
    ansible_connection: paramiko # don't need to apt-get sshpass
    ansible_user: colin
    ansible_python_interpreter: /usr/bin/python3
    nut_controller_address: 192.168.0.225
    k3s_registration_address: 192.168.0.8
    kv_url: 'https://chickenwaffles-vault-dev.vault.azure.net/'
    KEYVAULT_CLIENT_ID: "{{ lookup('azure_keyvault_secret', 'azure-keyvault-client-id', vault_url=kv_url) }}"
    KEYVAULT_SECRET: "{{ lookup('azure_keyvault_secret', 'azure-keyvault-secret', vault_url=kv_url) }}"
    nut_user_subscriber_password: "{{ lookup('azure_keyvault_secret', 'nut-user-subscriber-password', vault_url=kv_url) }}"
