# https://longhorn.io/docs/1.3.1/advanced-resources/deploy/customizing-default-settings/
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    allow-node-drain-with-last-healthy-replica: "true"
    default-data-locality: best-effort
    allow-volume-creation-with-degraded-availability: "false"
    replica-auto-balance: best-effort
    node-down-pod-deletion-policy: delete-both-statefulset-and-deployment-pod
