# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-vpn
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-external-secrets-stores
  # additional inheritance from infrastructure-external-secrets-stores
  # - namespaces
  # - repositories
  interval: 1h0m0s
  path: ./kubernetes/networking/vpn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-vpn-network-rules
  namespace: flux-system
spec:
  dependsOn:
    - name: networking-vpn
  # additional inheritance from infrastructure-vpn
  # - namespaces
  interval: 1h0m0s
  path: ./kubernetes/networking/vpn/network-rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
