apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: networking
  annotations:
    checkov.io/skip1: CKV_K8S_35=Prefer using secrets as files over secrets as environment variables
    secret.reloader.stakater.com/reload: cloudflare-tunnel-token
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.2.1
          args:
            - tunnel
            - run
          env:
            - name: TUNNEL_METRICS
              value: 0.0.0.0:2000 # creates /metrics and /ready endpoint
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-tunnel-token
                  key: token
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to the edge.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      dnsConfig:
        options:
          - name: ndots
            value: "1"
