# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: networking
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: cloudflare-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cloudflare-tunnel-token
