---
- name: Pushover | Create pushover folder
  become: true
  ansible.builtin.file:
    path: /etc/pushover
    state: directory
    owner: root
    group: nut
    mode: 0770

- name: Pushover | Copy Script
  become: true
  ansible.builtin.copy:
    src: pushover.sh
    dest: /etc/pushover/pushover.sh
    owner: root
    group: nut
    mode: 0750

- name: Pushover | Create creds file
  become: true
  ansible.builtin.blockinfile:
    path: /etc/pushover/pushover-config
    block: |
      api_token={{ pushover_app_token }}
      user_key={{ pushover_user_token }}
    create: true
    state: present
    owner: root
    group: nut
    mode: 0740
