compact: true
output: cli
quiet: true
skip-check:
  - CKV_K8S_8 # Liveness Probe should be configured
  - CKV_K8S_9 # Readiness probe should be configured
  - CKV_K8S_10 # CPU requests should be set
  - CKV_K8S_11 # CPU limits should be set
  - CKV_K8S_12 # Memory requests should be set
  - CKV_K8S_13 # Memory limits should be set
  - CKV_K8S_15 # Image Pull Policy should be Always
  - CKV_K8S_40 # Containers should run as a high UID to avoid host conflict
  - CKV_K8S_43 # Image should use digest
skip-path:
  - kubernetes/clusters/develop/flux-system
  - kubernetes/clusters/production/flux-system
  - kubernetes/infrastructure/longhorn/snapshot-controller
