---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: .venv/bin/ansible-lint
        language: python
        args: ["--force-color"]
        pass_filenames: false
        always_run: true
        files: \.(yml)$
        additional_dependencies:
          - .[core]
