---
repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: .venv/bin/ansible-lint
        language: python
        args: ["--force-color"]
        pass_filenames: false
        always_run: true
        files: \.(yml)$
        additional_dependencies:
          - .[core]
      - id: checkov-ansible
        name: Checkov Ansible
        description: This hook runs checkov on ansible items.
        entry: .venv/bin/checkov
        args: ["-d", "ansible", "--framework", "ansible"]
        language: python
        pass_filenames: false
        always_run: true
        require_serial: true
      - id: checkov-kubernetes
        name: Checkov Kubernetes
        description: This hook runs checkov on kubernetes items.
        entry: .venv/bin/checkov
        args: ["-d", "kubernetes", "--framework", "kubernetes", "helm", "kustomize", "yaml"]
        language: python
        pass_filenames: false
        always_run: true
        require_serial: true
      - id: end-of-file-fixer
        name: fix end of files
        description: ensures that a file is either empty, or ends with one newline.
        entry: .venv/bin/end-of-file-fixer
        language: python
        types: [text]
      - id: requirements-txt-fixer
        name: fix requirements.txt
        description: sorts entries in requirements.txt.
        entry: .venv/bin/requirements-txt-fixer
        language: python
        files: requirements.*\.txt$
      - id: trailing-whitespace
        name: trim trailing whitespace
        description: trims trailing whitespace.
        entry: .venv/bin/trailing-whitespace-fixer
        language: python
        types: [text]
      - id: yamllint
        name: yamllint
        entry: .venv/bin/yamllint
        language: python
        types: [yaml]
