# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-blob-splunk-secret
  namespace: monitor
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: azure-blob-splunk-secret
    creationPolicy: Owner
  data:
    - secretKey: azure_sa_name
      remoteRef:
        key: splunk-blob-storage-account
    - secretKey: azure_sa_secret_key
      remoteRef:
        key: splunk-blob-account-key
---
# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk-enterprise-license
  namespace: monitor
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: splunk-enterprise-license
    creationPolicy: Owner
  data:
    - secretKey: license.lic
      remoteRef:
        key: splunk-enterprise-license
---
# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk-otel-collector
  namespace: monitor
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: splunk-otel-collector
    creationPolicy: Owner
  data:
    - secretKey: splunk_platform_hec_token
      remoteRef:
        key: splunk-hec-token
