# example from: https://github.com/TobiasDeBruijn/HomelabKubernetes/blob/new/manifests/homelab/transmision.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: downloads
spec:
  replicas: 1
  selector:
    matchLabels:
      name: transmission
  template:
    metadata:
      labels:
        name: transmission
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
      - name: transmission-volume
        persistentVolumeClaim:
          claimName: transmission-volume-pvc
      - name: downloads-volume
        persistentVolumeClaim:
          claimName: transmission-downloads-pvc
      containers:
      - name: transmission
        image: ghcr.io/onedr0p/transmission:3.00@sha256:35daad26844c5294345c66771a719fe4a9cf72d3673125018598c61f327ffefe
        ports:
        - name: webui
          containerPort: 9091
          protocol: TCP
        env:
        - name: TRANSMISSION__DOWNLOAD_DIR
          value: /media/downloads/torrents/complete
        - name: TRANSMISSION__DOWNLOAD_QUEUE_SIZE
          value: "10"
        - name: TRANSMISSION__INCOMPLETE_DIR
          value: /media/downloads/torrents/incomplete
        - name: TRANSMISSION__INCOMPLETE_DIR_ENABLED
          value: "true"
        - name: TRANSMISSION__RATIO_LIMIT
          value: "0"
        - name: TRANSMISSION__RATIO_LIMIT_ENABLED
          value: "true"
        - name: TRANSMISSION__RPC_HOST_WHITELIST_ENABLED
          value: "false"
        - name: TRANSMISSION__SCRAPE_PAUSED_TORRENTS_ENABLED
          value: "false"
        - name: TRANSMISSION__SPEED_LIMIT_UP
          value: "50"
        - name: TRANSMISSION__SPEED_LIMIT_UP_ENABLED
          value: "true"
        volumeMounts:
        - name: transmission-volume
          mountPath: /config
        - name: downloads-volume
          mountPath: /media/downloads/torrents
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: downloads
spec:
  ports:
  - name: webui
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    name: transmission
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: transmission-ingress
  namespace: downloads
spec:
  ingressClassName: nginx
  rules:
  - host: media.${DOMAIN_NAME}
    http:
      paths:
      - path: /transmission
        pathType: Prefix
        backend:
          service:
            name: transmission
            port:
              name: webui
  tls:
  - hosts:
    - media.${DOMAIN_NAME}
