apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-pv
  namespace: downloads
spec:
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /shares/downloads/torrents
    server: ${NAS_IP}
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-pvc
  namespace: downloads
spec:
  storageClassName: ""
  volumeName: transmission-downloads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500G
