apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylar3-comics-pv
  namespace: media
spec:
  capacity:
    storage: 200G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /shares/comics
    server: ${NAS_IP}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mylar3-comics-pvc
  namespace: media
spec:
  storageClassName: ""
  volumeName: mylar3-comics-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200G
