---
- name: Weave GitOps | Download Binary
  ansible.builtin.unarchive:
    src: 'https://github.com/weaveworks/weave-gitops/releases/download/v{{ weave_gitops_version }}/gitops-linux-x86_64.tar.gz'
    dest: /usr/local/bin
    remote_src: yes
    include: gitops
    mode: 0755

- name: Flux | Setup | Binary
  ansible.builtin.include_role:
    name: nicholaswilde.flux2

- name: Flux | Check # noqa no-changed-when
# forces prerequisites
  ansible.builtin.command: 'flux check --kubeconfig "{{ home_path }}/.kube/config"'
  register: flux_check

- name: Flux | Deploy | Bootstrap Cmd
  ansible.builtin.shell: |
    export GITHUB_TOKEN={{ github_token }}

    flux bootstrap github --owner={{ github_owner }} \
    --repository={{ repository_name }} \
    --path={{ target_path }} \
    --branch={{ branch }} \
    --personal={{ personal }} \
    --private={{ private }} \
    --kubeconfig "{{ home_path }}/.kube/config" \
    --components-extra image-reflector-controller,image-automation-controller
  when: flux_check.rc == 0
