---
- name: Kubectl | Get Latest Version
  ansible.builtin.set_fact:
    kubectl_latest: "{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}"

- name: Kubectl | Download Binary
  ansible.builtin.get_url:
    url: 'https://dl.k8s.io/release/{{ kubectl_latest }}/bin/linux/amd64/kubectl'
    dest: /tmp
    mode: 0644

- name: Kubectl | Copy binary to /bin
  ansible.builtin.copy:
    src: /tmp/kubectl
    dest: /usr/local/bin
    owner: root
    group: root
    mode: u+x,g+x,o+rwx

# kubectl check if existing config exists on localhost
- name: Kubectl | Check if updated /tmp/kubeconfig file exists
  ansible.builtin.stat:
    path: /tmp/kubeconfig
  register: result

- name: Kubectl | Updating config file
  ansible.builtin.copy:
    src: /tmp/kubeconfig
    dest: '{{ kubectl_configpath }}/config'
    backup: yes
    mode: 0600 #originally 644
  when:
    - result.stat.exists
    - (result.stat.isdir is undefined) or (not result.stat.isdir)

- name: Kubectl | Remove tmp file
  ansible.builtin.file:
    path: /tmp/kubeconfig
    state: absent
