---
- name: Set Home Folder
  ansible.builtin.set_fact:
    home_path: "{{ lookup('env', 'HOME') }}"

- name: Install Kubectl
  include_tasks: kubectl.yml

- name: Flux Deployment
  include_tasks: flux.yml
