---
# yaml-language-server: $schema=../../../schemas/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitor-splunk-syslog
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-settings
    - name: monitor-splunk-app
  interval: 1h0m0s
  path: ./kubernetes/monitor/splunk-syslog/app
  prune: true
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
