---
# yaml-language-server: $schema=../../../../schemas/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
  namespace: secrets
spec:
  provider:
    azurekv:
      tenantId: ${AZURE_TENANT_ID}
      vaultUrl: "https://${AZURE_VAULT_NAME}.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-secrets-store-cred
          key: clientid
          namespace: secrets
        clientSecret:
          name: azure-secrets-store-cred
          key: clientsecret
          namespace: secrets
