# yaml-language-server: $schema=../../../schemas/secretproviderclass_v1.json
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-grafana-secret
  namespace: secrets-sync
spec:
  provider: azure
  secretObjects:
    - secretName: grafana-admin-creds # k8s-secret-name
      type: Opaque
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitor
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitor
      data:
        - objectName: grafana-admin-username # azure-key-name
          key: admin-user # k8s-key
        - objectName: grafana-admin-password
          key: admin-password
  parameters:
    usePodIdentity: "false" # dont unhash or you get boolean errors!
    keyvaultName: ${AZURE_VAULT_NAME}
    objects: |
      array:
        - |
          objectName: grafana-admin-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: grafana-admin-password
          objectType: secret
          objectVersion: ""
    tenantId: ${AZURE_TENANT_ID}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-grafana-secret
  namespace: secrets-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana-secret
  template:
    metadata:
      labels:
        name: grafana-secret
    spec:
      volumes:
        - name: grafana-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-grafana-secret
            nodePublishSecretRef:
              name: azure-secrets-store-cred
      containers:
        - name: azure-grafana-secret
          image: busybox:1.35.0
          command:
            - "/bin/sleep"
            - "10000"
          volumeMounts:
            - name: grafana-secret
              mountPath: /mnt/secrets-store
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
