# yaml-language-server: $schema=../../../../schemas/volume_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: sabnzbd-volume
  namespace: longhorn-system
spec:
  accessMode: rwo
  engineImage: longhornio/longhorn-engine:v1.6.1
  frontend: blockdev
  replicaAutoBalance: best-effort
  size: "513802240" # 512MB
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sabnzbd-volume-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 512Mi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sabnzbd-volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-volume-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: sabnzbd-volume-pv
