# Autoupdates applied in a k8s pod will be lost when the pod is removed or restarted, so
# autoupdate doesn't make sense in Kubernetes. However, outside of Kubernetes, we strongly
# recommend using autoupdate.
#
# The `ingress` block tells cloudflared which local service to route incoming
# requests to. For more about ingress rules, see
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
#
# *** Remember to create a DNS record pointing to cfargotunnel.com ***
#
# *** Top level ingress settings: ***
# originServerName prevents host issues when launching site - otherwise use noTLSVerify value.
#
# Troubleshooting
# This rule sends traffic to the built-in hello-world HTTP server. This can help debug connectivity
# issues. If hello.example.com resolves and tunnel.example.com does not, then the problem is
# in the connection from cloudflared to your local service, not from the internet to cloudflared.
#- hostname: example.com
#  service: hello_world
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: external
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: ${DOMAIN_NAME}-tunnel

    # Creds - imported from secret - don't modify
    credentials-file: /etc/cloudflared/creds/credentials.json

    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000

    # Refer to comments above
    no-autoupdate: true

    # Global ingress values
    originRequest:
      connectTimeout: 30s
      originServerName: '*.${DOMAIN_NAME}'

    # Add value for each new domain. service will be to ingress allowing external access
    ingress:
    - hostname: calibre.${DOMAIN_NAME}
      service: https://ingress-nginx-controller.ingress-nginx
    - hostname: jdownloader.${DOMAIN_NAME}
      service: https://ingress-nginx-controller.ingress-nginx
    - hostname: media.${DOMAIN_NAME}
      service: https://ingress-nginx-controller.ingress-nginx

    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
