apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-cloudflare-secrets
  namespace: external
spec:
  provider: azure
  secretObjects:
  - secretName: cloudflared-tunnel-creds # k8s-secret-name
    type: Opaque
    data:
    - objectName: cloudflared-tunnel-creds # azure-key-name - output from 'cloudflared tunnel create' cmd. Combines AccountTag, TunnelSecret & TunnelID
      key: credentials.json # k8s-key
  - secretName: cloudflare-api-token # k8s-secret-name
    type: Opaque
    data:
    - objectName: cloudflare-api-token # azure-key-name
      key: CF_API_TOKEN # k8s-key
  parameters:
    usePodIdentity: "false" # dont unhash or you get boolean errors!
    keyvaultName: ${AZURE_VAULT_NAME}
    objects: |
      array:
        - |
          objectName: cloudflared-tunnel-creds
          objectType: secret
          objectVersion: ""
        - |
          objectName: cloudflare-api-token
          objectType: secret
          objectVersion: ""
    tenantId: ${AZURE_TENANT_ID}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-cloudflare-secrets
  namespace: external
spec:
  replicas: 1
  selector:
    matchLabels:
      name: azure-cloudflare-secrets
  template:
    metadata:
      labels:
        name: azure-cloudflare-secrets
    spec:
      volumes:
      - name: cloudflare-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-cloudflare-secrets
          nodePublishSecretRef:
            name: azure-secrets-store-cred
      containers:
      - name: azure-cloudflare-secrets
        image: busybox:1.35.0
        command:
          - "/bin/sleep"
          - "10000"
        volumeMounts:
        - name: cloudflare-secrets
          mountPath: /mnt/secrets-store
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
