# yaml-language-server: $schema=../../../schemas/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-external-cloudflared
  namespace: flux-system
spec:
  dependsOn:
#    - name: namespaces
    - name: infrastructure-reloader
#    - name: secrets
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/external/cloudflared
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
---
# yaml-language-server: $schema=../../../schemas/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-external-dns
  namespace: flux-system
spec:
#  dependsOn:
#    - name: namespaces
#    - name: secrets
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/external/dns
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
