# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-external-cloudflared
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-external-secrets-stores
    - name: infrastructure-reloader
  # additional inheritance from infrastructure-external-secrets-stores:
  # - cluster-settings
  # - namespaces
  # - repositories
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/external/cloudflared
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
---
# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-external-cloudflared
  # additional inheritance from infrastructure-external-secrets-stores (via infrastructure-external-cloudflared)
  # - cluster-settings
  # - namespaces
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/external/dns
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
