apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: unifi-volume
  namespace: longhorn-system
spec:
  accessMode: rwx
  dataLocality: best-effort
  engineImage: longhornio/longhorn-engine:v1.3.0
  frontend: blockdev
  numberOfReplicas: 3
  replicaAutoBalance: best-effort
  size: "5368709120"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: unifi-volume-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
    volumeHandle: unifi-volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-customised
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-volume-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-customised
  volumeMode: Filesystem
  volumeName: unifi-volume-pv
