# yaml-language-server: $schema=../../../schemas/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-vpn
  namespace: flux-system
spec:
  interval: 1h0m0s
  dependsOn:
#    - name: helm
    - name: infrastructure-external-secrets-stores
#    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/vpn/app
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  timeout: 5m0s
  wait: true
