---
all:
  children:
    localhost:
    k3s_cluster:
  vars:
    kv_url: 'https://vaultkxtjt3mfw7.vault.azure.net/'

localhost:
  hosts:
    127.0.0.1
  vars:
    flux_version: 2.0.1
    weave_gitops_version: 0.30.0
    ansible_connection: local
    branch: refactor
    target_path: kubernetes/clusters/production

k3s_cluster:
  hosts:
    monty:
      nut_controller_node: true
      k3s_control_node: true
      ansible_host: 192.168.0.225
    crackers:
      ansible_host: 192.168.0.226
    mindy:
      ansible_host: 192.168.0.227
  vars:
    k3s_release_version: v1.26.6+k3s1
    ansible_connection: paramiko # don't need to apt-get sshpass
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    nut_controller_address: 192.168.0.225
    k3s_registration_address: 192.168.0.225
    pushover_app_token: "{{ lookup('azure_keyvault_secret', 'pushover-app-token', vault_url=kv_url) }}"
    pushover_user_token: "{{ lookup('azure_keyvault_secret', 'pushover-user-token', vault_url=kv_url) }}"
    nut_user_controller_password: "{{ lookup('azure_keyvault_secret', 'nut-user-controller-password', vault_url=kv_url) }}"
