---
# Values common to both dev and prod

# flux creds
github_token: "{{ lookup('azure_keyvault_secret', 'github-token', vault_url=kv_url) }}"

# flux setup
app_ver: "{{ flux_version }}"

# flux deploy
github_owner: cfergs
repository_name: kubernetes-homelab
personal: true
private: true
