---
# flux setup - app_arch & app_os tweaks make nicholaswilde.flux2 role compatibile with MacOS. Don't mess with these values
app_arch: "{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else 'arm64' }}"
app_os: "{{ ansible_facts['system'] | lower }}"
app_ver: "{{ flux_version }}"
