---
# Values common to both dev and prod

# flux creds
github_token: "{{ lookup('azure_keyvault_secret', 'github-token', vault_url=kv_url) }}"

# flux setup
app_arch: "{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else 'arm64' }}"
app_platform: "{{ ansible_facts['system'] | lower }}" # either darwin or linux
app_ver: "{{ flux_version }}"

# flux deploy
github_owner: cfergs
repository_name: kubernetes-homelab
personal: true
private: true
