apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: downloads
data:
  qBittorrent.conf: |
    [BitTorrent]
    Session\AnonymousModeEnabled=true
    Session\DefaultSavePath=/media/downloads/torrents/complete
    Session\GlobalMaxRatio=0
    Session\MaxActiveDownloads=10
    Session\MaxActiveTorrents=10
    Session\MaxConnections=501
    Session\MaxConnectionsPerTorrent=101
    Session\MaxUploads=21
    Session\MaxUploadsPerTorrent=10
    Session\PerformanceWarning=true
    Session\Port=50413
    Session\QueueingSystemEnabled=true
    Session\TempPath=/media/downloads/torrents/incomplete
    Session\TempPathEnabled=true

    [Core]
    AutoDeleteAddedTorrentFile=IfAdded

    [LegalNotice]
    Accepted=true

    [Meta]
    MigrationVersion=4

    [Network]
    PortForwardingEnabled=false
    Proxy\OnlyForTorrents=false

    [Preferences]
    Advanced\RecheckOnCompletion=false
    Advanced\trackerPort=9000
    Advanced\trackerPortForwarding=false
    Connection\ResolvePeerCountries=true
    General\Locale=en
    WebUI\Address=*
    WebUI\AlternativeUIEnabled=false
    WebUI\AuthSubnetWhitelist=0.0.0.0/0
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\BanDuration=3600
    WebUI\CSRFProtection=true
    WebUI\ClickjackingProtection=true
    WebUI\CustomHTTPHeadersEnabled=false
    WebUI\HTTPS\Enabled=false
    WebUI\HostHeaderValidation=false
    WebUI\LocalHostAuth=false
    WebUI\MaxAuthenticationFailCount=5
    WebUI\Port=8080
    WebUI\ReverseProxySupportEnabled=false
    WebUI\SecureCookie=true
    WebUI\ServerDomains=*
    WebUI\SessionTimeout=3600
    WebUI\TrustedReverseProxiesList=
    WebUI\UseUPnP=false
