apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-home-automation
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: helm
    - name: cluster-settings
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/production/home-automation
  prune: true
  wait: true
  timeout: 5m0s
  validation: client
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  patches:
  - patch: |-
      - op: replace
        path: /spec/size
        value: "1368709120"
    target:
      kind: Volume
      name: automation-volume
  - patch: |-
      - op: replace
        path: /spec/capacity/storage
        value: 1Gi
    target:
      kind: PersistentVolume
      name: automation-volume-pv
  - patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 1Gi
    target:
      kind: PersistentVolumeClaim
      name: automation-volume-pvc
