apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/production
  prune: true
  validation: client
patches:
  - patch: |-
      - op: replace
        path: /parameters/numberOfReplicas
        value: "1"
    target:
      kind: StorageClass
      name: longhorn-customised
      namespace: longhorn-system
