# yaml-language-server: $schema=../../../schemas/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/namespaces
  prune: true
  timeout: 5m0s
  validation: client
