# yaml-language-server: $schema=../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/networking
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
