---
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.0
  - src: nicholaswilde.flux2
    version: v1.0.11

collections:
  - name: ansible.posix
    version: 1.4.0
    source: https://galaxy.ansible.com
  - name: kubernetes.core
    version: 2.3.2
    source: https://galaxy.ansible.com
