# yaml-language-server: $schema=../../../../schemas/volume_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: prowlarr-volume
  namespace: longhorn-system
spec:
  accessMode: rwo
  engineImage: longhornio/longhorn-engine:v1.6.1
  frontend: blockdev
  replicaAutoBalance: best-effort
  size: "1073741824" # 1GB
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prowlarr-volume-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: prowlarr-volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prowlarr-volume-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: prowlarr-volume-pv
