apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- reloader
- kube-system
- secrets-sync # central location of creds and synced to where needed
- cert-manager
- metallb
- ingress
- external # dependent on ingress
- longhorn
- downloads-vpn
