apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- csi-secrets-driver  # cannot get consistent install via k8s manifests & helm wont work
- azure-secrets
- cert-manager
- metallb
- ingress
- longhorn
