# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-system # reloader
  - cert-manager
  - metallb
  - ingress
  - external # dependent on ingress
  - longhorn
  - downloads-vpn
