apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- reloader
- csi-secrets-driver  # cannot get consistent install via k8s manifests & helm wont work
- azure-secrets
- secrets-sync # central location of creds and synced to where needed
- cert-manager
- metallb
- ingress
- external # dependent on ingress
- longhorn
- downloads-vpn
