apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: secrets-sync
spec:
  chart:
    spec:
      chart: reflector
      interval: 5m
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      version: 6.1.47
  interval: 5m
