apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-splunk-secrets
  namespace: secrets-sync
spec:
  provider: azure
  secretObjects:
  - secretName: splunk-monitor-secret # k8s-secret-name
    type: Opaque
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitor
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitor
    data:
    - objectName: splunk-hec-token
      key: hec_token # k8s-key
    - objectName: splunk-idxc-secret
      key: idxc_secret
    - objectName: splunk-pass4SymmKey
      key: pass4SymmKey
    - objectName: splunk-admin-password
      key: password
    - objectName: splunk-shc-secret
      key: shc_secret
  - secretName: splunk-otel-collector
    type: Opaque
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitor
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: monitor
    data:
    - objectName: splunk-hec-token
      key: splunk_platform_hec_token
  parameters:
    usePodIdentity: "false" # dont unhash or you get boolean errors!
    keyvaultName: ${AZURE_VAULT_NAME}
    objects: |
      array:
        - |
          objectName: splunk-hec-token
          objectType: secret
          objectVersion: ""
        - |
          objectName: splunk-idxc-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: splunk-pass4SymmKey
          objectType: secret
          objectVersion: ""
        - |
          objectName: splunk-admin-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: splunk-shc-secret
          objectType: secret
          objectVersion: ""
    tenantId: ${AZURE_TENANT_ID}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-splunk-secrets
  namespace: secrets-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      name: azure-splunk-secrets
  template:
    metadata:
      labels:
        name: azure-splunk-secrets
    spec:
      volumes:
      - name: azure-splunk-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-splunk-secrets
          nodePublishSecretRef:
            name: azure-secrets-store-cred
      containers:
      - name: azure-splunk-secrets
        image: busybox:1.35.0
        command:
          - "/bin/sleep"
          - "10000"
        volumeMounts:
        - name: azure-splunk-secrets
          mountPath: /mnt/secrets-store
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
