apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-automation
data:
  mosquitto.conf: |
    #bind_address

    # Port to use for default listener
    listener 1883

    # allow anonymous access
    allow_anonymous true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-automation
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.15-openssl@sha256:9f39fb6724428c717e598522417010d5799409a761144175ed8f107e8827d381
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      dnsConfig:
        options:
          - name: ndots
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${MQTT_IP}
  namespace: home-automation
  labels:
    app: mosquitto
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 1883
      targetPort: 1883
  selector:
    app: mosquitto
  type: LoadBalancer
