# yaml-language-server: $schema=../../../schemas/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 1h0m0s
---
# yaml-language-server: $schema=../../../schemas/helmrelease_v2beta1.json
# this needs to be done as part of initial deployment so prometheus rules
# can be created by products prior to installing prometheus itself
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-crds
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-operator-crds
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 5.0.0
  interval: 1h0m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
