---
- name: Cluster | Crackers | Zigbee label
  become: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiversion: v1
      kind: Node
      metadata:
        name: crackers
        labels:
          usb: zigbee
    kubeconfig: "{{ kube_file }}"
  when:
    - k3s_control_node is defined
    - k3s_control_node

# The following steps are needed to create namespace and secrets needed for external-secrets operator to connect to azure keyvault
- name: Create secret namespace
  become: true
  kubernetes.core.k8s:
    name: secrets
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kube_file }}"
  when:
    - k3s_control_node is defined
    - k3s_control_node

# Both these values are pulled from the env values used as part of initially running ansible
- name: Create Azure-Keyvault secret
  become: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: azure-secrets-store-cred
        namespace: secrets
      type: Opaque
      data:
        clientid: "{{ azure_client_id | b64encode }}"
        clientsecret: "{{ azure_secret | b64encode }}"
    kubeconfig: "{{ kube_file }}"
  no_log: true
  when:
    - k3s_control_node is defined
    - k3s_control_node
  changed_when: false

# Doing this because secret contains secret/non secret values and i don't feel like sticking all them in keyvault
# secret expires 30/6/2025
- name: Create flux weave gitops secret
  become: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: oidc-auth
        namespace: flux-system
      type: Opaque
      stringData:
        claimGroups: roles
        claimUsername: email
        clientID: "{{ weave_gitops_app_clientid }}"
        customScopes: openid,profile,email
        clientSecret: "{{ weave_gitops_app_clientsecret }}"
        issuerURL: "https://login.microsoftonline.com/{{ azure_tenant }}/v2.0"
        redirectURL: "https://flux.{{ homelab_domain_name }}/oauth2/callback"
    kubeconfig: "{{ kube_file }}"
  no_log: true
  when:
    - k3s_control_node is defined
    - k3s_control_node
  changed_when: false
