# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  namespace: monitor
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: grafana-admin-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: grafana-admin-password
---
# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-azure-auth
  namespace: monitor
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: grafana-azure-auth
    creationPolicy: Owner
  data:
    - secretKey: clientid
      remoteRef:
        key: grafana-dashboard-app-clientid
    - secretKey: clientsecret
      remoteRef:
        key: grafana-dashboard-app-clientsecret
---
# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-thanos-blob-creds
  namespace: monitor
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: prometheus-thanos-blob-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data: # format that thanos helmrelease needs it in
        objstore.yml: |
          type: AZURE
          config:
            storage_account: "{{ .storage_account_name }}"
            storage_account_key: "{{ .storage_account_key }}"
            container: "prometheus"
  data:
    - secretKey: storage_account_name
      remoteRef:
        key: prometheus-blob-storage-account
    - secretKey: storage_account_key
      remoteRef:
        key: prometheus-blob-account-key
