# yaml-language-server: $schema=../../../schemas/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-coredns-config
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/kube-system/coredns
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
# yaml-language-server: $schema=../../../schemas/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure-reloader
  namespace: flux-system
spec:
#  dependsOn:
#    - name: helm
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/kube-system/reloader
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
