# yaml-language-server: $schema=../../../schemas/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: reloader
      version: 1.0.27
      interval: 1h0m0s
      sourceRef:
        kind: HelmRepository
        name: reloader
        namespace: flux-system
