apiVersion: v1
kind: PersistentVolume
metadata:
  name: jdownloader-downloads-pv
  namespace: downloads
spec:
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /shares/downloads/jdownloader
    server: ${NAS_IP}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jdownloader-downloads-pvc
  namespace: downloads
spec:
  storageClassName: ""
  volumeName: jdownloader-downloads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500G
