apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: jdownloader-volume
  namespace: longhorn-system
spec:
  accessMode: rwx
  engineImage: longhornio/longhorn-engine:v1.3.2
  frontend: blockdev
  replicaAutoBalance: best-effort
  size: "512000000" # 512MB
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jdownloader-volume-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 512Mi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: jdownloader-volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jdownloader-volume-pvc
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: jdownloader-volume-pv
