# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-ingress.yaml # special rule for weave gitops url
  - longhorn-ingress.yaml # special rule for longhorn mgmt url
