# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-azure-auth
  namespace: flux-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: oidc-auth # weave-gitops expects this name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        claimGroups: roles
        claimUsername: email
        clientID: "{{ .clientid }}"
        clientSecret: "{{ .clientsecret }}"
        customScopes: openid,profile,email
        issuerURL: "https://login.microsoftonline.com/{{ .tenantid }}/v2.0"
        redirectURL: "https://flux.{{ .domain_name }}/oauth2/callback"
        tokenDuration: 1h0m0s
  data:
    - secretKey: clientid
      remoteRef:
        key: weave-gitops-app-clientid
    - secretKey: clientsecret
      remoteRef:
        key: weave-gitops-app-clientsecret
    - secretKey: domain_name
      remoteRef:
        key: homelab-domainname
    - secretKey: tenantid
      remoteRef:
        key: azuread-tenantid
