apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  labels:
    longhornvolume: config-file-volume
    #recurring-job-group.longhorn.io/backup: enabled
  name: config-file-volume
  namespace: longhorn-system
spec:
  accessMode: rwx
  dataLocality: best-effort
  engineImage: longhornio/longhorn-engine:v1.3.0
  frontend: blockdev
  numberOfReplicas: 2
  size: "1368709120"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: config-file-pv
spec:
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: config-file-volume
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-customised
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-file-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: config-file-pv
  storageClassName: longhorn-customised
  volumeMode: Filesystem
