apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads-pv
  namespace: media
spec:
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /shares/downloads
    server: ${NAS_IP}
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads-pvc
  namespace: media
spec:
  storageClassName: ""
  volumeName: sonarr-downloads-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500G
