# https://github.com/Koenkk/zigbee2mqtt/discussions/10899
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-automation
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
      - name: automation-volume
        persistentVolumeClaim:
          claimName: automation-volume-pvc
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:1.26.0
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: Australia/Perth
        - name: ZIGBEE2MQTT_CONFIG_FRONTEND_PORT
          value: '8080'
        - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
          value: mqtt://mosquitto.home-automation:1883
        - name: ZIGBEE2MQTT_CONFIG_PERMIT_JOIN
          value: 'true'
        - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
          value: tcp://zigbee-ser2sock:10000
        - name: ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL
          value: '20'
        - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT
          value: 'true'
        - name: ZIGBEE2MQTT_CONFIG_ADVANCED_IKEA_OTA_USE_TEST_URL
          value: 'false'
        - name: ZIGBEE2MQTT_CONFIG_LOG_OUTPUT
          value: 'console'
        volumeMounts:
        - name: automation-volume
          mountPath: /app/data
          subPath: configs/zigbee2mqtt
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: home-automation
  labels:
    app: zigbee2mqtt
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: zigbee2mqtt
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zigbee2mqtt-ingress
  namespace: home-automation
spec:
  entryPoints:
  - web
  routes:
    - match: PathPrefix(`/zigbee2mqtt`)
      kind: Rule
      services:
        - name: zigbee2mqtt
          port: 8080
      middlewares:
        - name: zigbee2mqtt-stripprefixregex
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: zigbee2mqtt-stripprefixregex
  namespace: home-automation
spec:
  stripPrefixRegex:
    regex:
      - "/[a-z0-9_]+"
