apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: zigbee2mqtt-config-volume
  name: zigbee2mqtt-config-volume
  namespace: longhorn-system
spec:
  accessMode: rwx
  storageClassName: longhorn-customised
  engineImage: longhornio/longhorn-engine:v1.2.4
  frontend: blockdev
  numberOfReplicas: 2
  size: "104857600"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zigbee2mqtt-config-pv
spec:
  capacity:
    storage: 100Mi
  csi:
    driver: driver.longhorn.io
    volumeHandle: zigbee2mqtt-config-volume
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-customised
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zigbee2mqtt-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: zigbee2mqtt-config-pv
  storageClassName: longhorn-customised
  volumeMode: Filesystem
---
# https://github.com/Koenkk/zigbee2mqtt/discussions/10899
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-automation
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      volumes:
      - name: automation-volume
        persistentVolumeClaim:
          claimName: zigbee2mqtt-config-pvc
      - name: zigbee2mqtt-udev
        hostPath:
          path: /run/udev
      - name: ttyusb
        hostPath:
          path: /dev/ttyUSB0
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: Australia/Perth
        - name: ZIGBEE2MQTT_CONFIG_FRONTEND_HOST
          value: '0.0.0.0'
        - name: ZIGBEE2MQTT_CONFIG_FRONTEND_PORT
          value: '8080'
        - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
          value: mqtt://mosquitto.home-automation:1883
        - name: ZIGBEE2MQTT_CONFIG_PERMIT_JOIN
          value: 'true'
        - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
          value: /dev/ttyUSB0
        - name: ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL
          value: '20'
        - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT
          value: 'true'
        - name: ZIGBEE2MQTT_CONFIG_ADVANCED_IKEA_OTA_USE_TEST_URL
          value: 'false'
        - name: ZIGBEE2MQTT_CONFIG_LOG_OUTPUT
          value: 'console'
        volumeMounts:
        - name: automation-volume
          mountPath: /app/data
          subPath: zigbee2mqtt
        - name: zigbee2mqtt-udev
          mountPath: /run/udev
        - name: ttyusb
          mountPath: /dev/ttyUSB0
---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: home-automation
  labels:
    app: zigbee2mqtt
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: zigbee2mqtt
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: zigbee2mqtt-ingress
#  namespace: home-automation
#spec:
#  entryPoints:
#  - web
#  routes:
#    - match: PathPrefix(`/zigbee2mqtt`)
#      kind: Rule
#      services:
#        - name: zigbee2mqtt
#          port: 8080
