apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: downloads-gateway
  namespace: downloads-vpn
spec:
  chart:
    spec:
      chart: pod-gateway
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      version: 5.6.2
  interval: 15m
  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.7.0@sha256:ce4871ccdfb98e8dcb5330125a06954ca3b40d9cff3235fb39ac2ba33feff0ff

    additionalContainers:
      gluetun:
        image: qmcgaw/gluetun:v3.31.0@sha256:9ef4853dab38fb829d481283e9f154243b61e54e3fa7973fa9bfb966d08f9f19
        env:
          - name: VPN_TYPE
            value: openvpn
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off" # unable to bind to 127.0.0.1:53 as used by host OS
          - name: VPN_SERVICE_PROVIDER
            value: nordvpn
          - name: SERVER_REGIONS
            value: Australia
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: nordvpn
                key: username
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nordvpn
                key: password
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
    addons:
      netshoot:
        enabled: true

    routed_namespaces:
      - downloads
      - media
      - test

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16"
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: tun0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: 1194

    webhook:
      gatewayAnnotation: setGateway
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.6.0
