# yaml-language-server: $schema=../../../schemas/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: downloads-gateway
  namespace: downloads-vpn
spec:
  chart:
    spec:
      chart: pod-gateway
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      version: 5.6.2
  interval: 15m
  values:
    image:
      repository: ghcr.io/angelnu/pod-gateway
      tag: v1.8.1@sha256:baba1f27d821e8cbd27be115156425041455d1281115a8ca8d3bca9379a3ee24

    additionalContainers:
      gluetun:
        image: qmcgaw/gluetun:v3.32@sha256:bb2915294ed4d3d5ef29e1423f4ff751f861a871dd64ef3e662dc4c2279a34b3
        env:
          - name: VPN_TYPE
            value: openvpn
          - name: FIREWALL
            value: "off"
          - name: DOT
            value: "off" # unable to bind to 127.0.0.1:53 as used by host OS
          - name: VPN_SERVICE_PROVIDER
            value: nordvpn
          - name: SERVER_REGIONS
            value: Australia
          - name: OPENVPN_USER
            valueFrom:
              secretKeyRef:
                name: nordvpn
                key: username
          - name: OPENVPN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nordvpn
                key: password
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
    addons:
      netshoot:
        enabled: true

    routed_namespaces:
      - downloads
      - media

    settings:
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16"
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_INTERFACE: tun0
      VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
      VPN_TRAFFIC_PORT: 1194

    webhook:
      gatewayAnnotation: setGateway
      gatewayLabel: setGateway
      image:
        repository: ghcr.io/angelnu/gateway-admision-controller
        tag: v3.8.0
