apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv
  namespace: cert-manager
spec:
  provider: azure
  secretObjects:
  - secretName: cloudflare-api-token # k8s secretname
    type: Opaque
    data:
    - objectName: cloudflare-api-token # azure secretname
      key: api-token
  parameters:
    usePodIdentity: "false" # dont unhash or you get boolean errors!
    keyvaultName: ${AZURE_VAULT_NAME}
    objects: |
      array:
        - |
          objectName: cloudflare-api-token
          objectType: secret
          objectVersion: ""
    tenantId: ${AZURE_TENANT_ID}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-cloudflare-api-secret
  namespace: cert-manager
  labels:
    app: azure-cloudflare-api-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-cloudflare-api-secret
  template:
    metadata:
      labels:
        app: azure-cloudflare-api-secret
    spec:
      volumes:
      - name: azure-cloudflare-api-secret
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: azure-kv
          nodePublishSecretRef:
            name: azure-secrets-store-cred
      containers:
      - name: azure-cloudflare-api-secret
        image: busybox:1.35.0
        command:
          - "/bin/sleep"
          - "10000"
        volumeMounts:
        - name: azure-cloudflare-api-secret
          mountPath: /mnt/secrets-store
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
