---
# yaml-language-server: $schema=../../../../schemas/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitor
spec:
  chart:
    spec:
      chart: thanos
      version: 12.13.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 1h
  maxHistory: 2
  timeout: 10m
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # From: https://github.com/bitnami/charts/tree/main/bitnami/thanos
    # Value params listed in order shown in doco

    # Thanos Common params
    commonAnnotations:
      secret.reloader.stakater.com/reload: prometheus-thanos-blob-creds
    existingObjstoreSecret: prometheus-thanos-blob-creds

    # Thanos Query params
    query:
      enabled: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      dnsDiscovery:
        sidecarsService: prometheus-thanos-discovery
        sidecarsNamespace: monitor

    # Thanos Query Frontend params
    queryFrontend:
      enabled: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"

    # Thanos Compactor params
    compactor:
      enabled: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      extraFlags:
        - --compact.concurrency=4
        - --delete-delay=30m
      retentionResolutionRaw: 30d
      retentionResolution5m: 60d
      retentionResolution1h: 90d
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi

    # Thanos Store Gateway params
    storegateway:
      enabled: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      persistence:
        enabled: true
        storageClass: local-path
        size: 10Gi

    # Thanos Metrics params
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
