# yaml-language-server: $schema=../../../../schemas/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: splunk-otel-collector
  namespace: monitor
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: splunk-otel-collector
      version: 0.80.0
      interval: 1h0m0s
      sourceRef:
        kind: HelmRepository
        name: splunk-otel-collector-chart
        namespace: flux-system
  values:
    clusterName: k3s_homelab
    environment: production
    logsEngine: otel
    splunkPlatform:
      endpoint: https://splunk-hec.${DOMAIN_NAME}/services/collector/event
      index: k8s_events
      metricsEnabled: false
      logsEnabled: true
    logsCollection:
      containers:
        enabled: true
        excludePaths:
          - "/var/log/pods/vpn_vpn-*/*/*.log" # longhorn and vpn generate too many events to make them useful
          - "/var/log/pods/kube-system_snapshot-controller*/*/*.log"
          - "/var/log/pods/longhorn-system_longhorn-manager*/*/*.log"
          - "/var/log/pods/nginx-internal_logging-nginx-internal-controller*/*/*.log"

      journald:
        enabled: true
        units:
          - name: k3s
            priority: info
          - name: nut-driver
            priority: info
          - name: nut-server
            priority: info
          - name: stale-containers
            priority: info
          - name: ssh
            priority: info
        directory: /var/log/journal
        index: k8s_events

    secret:
      create: false
      name: splunk-otel-collector
      validateSecret: false
