# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk-otel-collector
  namespace: monitor
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: splunk-otel-collector
    creationPolicy: Owner
  data:
    - secretKey: splunk_platform_hec_token
      remoteRef:
        key: splunk-hec-token
