apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-books-pv
  namespace: media
spec:
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /shares/books
    server: ${NAS_IP}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-books-pvc
  namespace: media
spec:
  storageClassName: ""
  volumeName: readarr-books-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50G
