apiVersion: v1
kind: PersistentVolume
metadata:
  name: readarr-downloads-pv
  namespace: media
spec:
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteMany
  nfs:
    path: /shares/downloads
    server: ${NAS_IP}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-downloads-pvc
  namespace: media
spec:
  storageClassName: ""
  volumeName: readarr-downloads-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500G
