# yaml-language-server: $schema=../../schemas/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: csi-secrets-store-provider-azure
  namespace: flux-system
spec:
  url: https://azure.github.io/secrets-store-csi-driver-provider-azure/charts
  interval: 1h0m0s
