# yaml-language-server: $schema=../../schemas/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-at-home-charts
  namespace: flux-system
spec:
  url: https://k8s-at-home.com/charts
  interval: 10m
