# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - angelnu-charts.yaml
  - csi-secrets-store-provider-azure.yaml
  - ingress-nginx.yaml
  - kubernetes-reflector.yaml
  - prometheus-community.yaml
  - reloader.yaml
  - splunk-operator.yaml
  - splunk-otel-collector.yaml
