apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: sonarr-volume
  namespace: longhorn-system
spec:
  accessMode: rwx
  engineImage: longhornio/longhorn-engine:v1.3.0
  frontend: blockdev
  replicaAutoBalance: best-effort
  size: "1073741824" # 1GB
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: sonarr-volume-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: sonarr-volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarr-volume-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: sonarr-volume-pv
