- name: OS Shutdown
  hosts: k3s_cluster
  become: true
  pre_tasks:
    - name: Get local user for running scripts
      ansible.builtin.set_fact:
        local_username: "{{ lookup('env', 'USER') }}"
      delegate_to: localhost

  roles:
    - os_shutdown
