apiVersion: longhorn.io/v1beta1
kind: Volume
metadata:
  labels:
    longhornvolume: config-file-volume
    #recurring-job-group.longhorn.io/backup: enabled
  name: config-file-volume
  namespace: longhorn-system
spec:
  accessMode: rwx
  storageClassName: longhorn-customised
  engineImage: longhornio/longhorn-engine:v1.2.4
  frontend: blockdev
  numberOfReplicas: 2
  size: "5368709120"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: config-file-pv
spec:
  capacity:
    storage: 5Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: config-file-volume
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "2"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-customised
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-file-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: config-file-pv
  storageClassName: longhorn-customised
  volumeMode: Filesystem
