# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-flux-gitops
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-ingress-internal
    - name: infrastructure-reloader
  # additional inheritance from infrastructure-ingress-internal
  # - cluster-settings
  # - infrastructure-external-secrets-stores
  # - namespaces
  # - repositories
  interval: 1h
  path: ./kubernetes/infrastructure/flux/gitops
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
