---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-transcode-volume-pvc
  namespace: media
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
