# yaml-language-server: $schema=../../../../schemas/volume_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: jellyfin-volume
  namespace: longhorn-system
spec:
  accessMode: rwo
  engineImage: longhornio/longhorn-engine:v1.4.2
  frontend: blockdev
  replicaAutoBalance: best-effort
  size: "10737418240" # 10Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jellyfin-volume-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: jellyfin-volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jellyfin-volume-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: jellyfin-volume-pv
