# when deleting a splunk deployment it will delete the existing secret. This then causes it to create a secret with random values if secret doesnt exist
# trying to force this to create first so it doesnt get this chance.
# yaml-language-server: $schema=../../../../schemas/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk-monitor-secret
  namespace: monitor
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: splunk-monitor-secret
    creationPolicy: Owner
  data:
    - secretKey: hec_token
      remoteRef:
        key: splunk-hec-token
    - secretKey: idxc_secret
      remoteRef:
        key: splunk-idxc-secret
    - secretKey: pass4SymmKey
      remoteRef:
        key: splunk-pass4SymmKey
    - secretKey: password
      remoteRef:
        key: splunk-admin-password
    - secretKey: shc_secret
      remoteRef:
        key: splunk-shc-secret
