# yaml-language-server: $schema=../../../../schemas/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: splunk-operator
  namespace: monitor
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: splunk-operator
      version: 2.5.2 # splunk 9.1.3
      interval: 1h0m0s
      sourceRef:
        kind: HelmRepository
        name: splunk-operator
        namespace: flux-system
  values:
    splunkOperator:
      persistentVolumeClaim:
        storageClassName: local-path

      volumes:
        - name: app-staging
          persistentVolumeClaim:
            claimName: splunk-operator-app-download

      volumeMounts:
        - mountPath: /opt/splunk/appframework/
          name: app-staging
