# yaml-language-server: $schema=../../../../schemas/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: splunk-operator
  namespace: monitor
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: splunk-operator
      version: 2.4.0 # splunk 9.1.1
      interval: 1h0m0s
      sourceRef:
        kind: HelmRepository
        name: splunk-operator
        namespace: flux-system
  values:
      volumes:
        - name: app-staging
          persistentVolumeClaim:
            claimName: splunk-operator-app-download

      volumeMounts:
        - mountPath: /opt/splunk/appframework/
          name: app-staging
