---
# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-external-secrets # install crds
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
    - name: repositories
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/secrets/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-external-secrets-stores
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-external-secrets # needs crds to be installed first
  # additional inheritance from infrastructure-external-secrets
  # - namespaces
  # - repositories
  interval: 1h0m0s
  path: ./kubernetes/infrastructure/secrets/stores
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: special-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
