# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - angelnu-charts.yaml
  - external-secrets.yaml
  - ingress-nginx.yaml
  - reloader.yaml
  - splunk-operator.yaml
  - splunk-otel-collector.yaml
