---
# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitor-splunk-app
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-reloader
    - name: monitor-splunk-operator # deploys splunk crds
  # additional inheritance from infrastructure-splunk-operator
  # - cluster-settings
  # - infrastructure-ingress-logging
  # - namespaces
  # - repositories
  interval: 1h0m0s
  path: ./kubernetes/monitor/splunk/app
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: ConfigMap
        name: special-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitor-splunk-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-ingress-logging
  # additional inheritance from infrastructure-external-secrets-stores (via infrastructure-ingress-logging)
  # - cluster-settings
  # - namespaces
  # - repositories
  interval: 1h0m0s
  path: ./kubernetes/monitor/splunk/splunk-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
