---
# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitor-splunk-app
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-settings
    - name: infrastructure-external-secrets-stores
    - name: infrastructure-ingress-logging
    - name: infrastructure-reloader
    - name: monitor-splunk-operator # deploys splunk crds
  interval: 1h0m0s
  path: ./kubernetes/monitor/splunk/app
  postBuild: # https://github.com/fluxcd/helm-operator/issues/120
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitor-splunk-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-external-secrets-stores
    - name: infrastructure-ingress-logging
    - name: namespaces
    - name: repositories
  interval: 1h0m0s
  path: ./kubernetes/monitor/splunk/splunk-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
