# https://github.com/Koenkk/zigbee2mqtt/discussions/10899
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  serviceName: zigbee2mqtt
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: zigbee2mqtt-volume
          persistentVolumeClaim:
            claimName: zigbee2mqtt-volume-pvc
      containers:
        - name: zigbee2mqtt
          image: ghcr.io/koenkk/zigbee2mqtt:1.30.4@sha256:b9e8a132de8369a6f9616e5ec432a8c27d0060602041d992216b1713d167fae5
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: ${TIMEZONE}
            - name: ZIGBEE2MQTT_CONFIG_FRONTEND_PORT
              value: '8080'
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
              value: mqtt://mosquitto.home-automation.svc.cluster.local:1883
            - name: ZIGBEE2MQTT_CONFIG_PERMIT_JOIN
              value: 'true'
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
              value: tcp://zigbee-ser2sock.home-automation.svc.cluster.local:10000
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL
              value: '20'
            - name: ZIGBEE2MQTT_CONFIG_HOMEASSISTANT
              value: 'true'
            - name: ZIGBEE2MQTT_CONFIG_ADVANCED_IKEA_OTA_USE_TEST_URL
              value: 'false'
            - name: ZIGBEE2MQTT_CONFIG_LOG_OUTPUT
              value: 'console'
          volumeMounts:
            - name: zigbee2mqtt-volume
              mountPath: /app/data
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      dnsConfig:
        options:
          - name: ndots
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: zigbee2mqtt
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: zigbee2mqtt-ingress
  namespace: home-automation
spec:
  ingressClassName: nginx-internal
  rules:
    - host: hass.${DOMAIN_NAME}
      http:
        paths:
          - path: /zigbee2mqtt(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: zigbee2mqtt
                port:
                  number: 8080
