# yaml-language-server: $schema=../../../../schemas/volume_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  name: zigbee2mqtt-volume
  namespace: longhorn-system
spec:
  accessMode: rwo
  engineImage: longhornio/longhorn-engine:v1.5.1
  frontend: blockdev
  replicaAutoBalance: best-effort
  size: "134217728" # 128MB
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zigbee2mqtt-volume-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 128Mi
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: zigbee2mqtt-volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn-static
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zigbee2mqtt-volume-pvc
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: longhorn-static
  volumeMode: Filesystem
  volumeName: zigbee2mqtt-volume-pv
