---
- name: Install Kubernetes
  ansible.builtin.include_role:
    name: xanmanning.k3s

- name: Cluster | kubeconfig | copy config file to localhost
  become: true
  run_once: true
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "/tmp/kubeconfig"
    flat: true
  when:
    - k3s_control_node is defined
    - k3s_control_node

- name: Cluster | kubeconfig | update kubeconfig with the right IPv4 address
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "/tmp/kubeconfig"
    regexp: "https://127.0.0.1:6443"
    replace: "https://{{ k3s_registration_address }}:6443"

- name: Cluster | Crackers | Zigbee label
  become: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiversion: v1
      kind: Node
      metadata:
        name: crackers
        labels:
          usb: zigbee
    kubeconfig: "{{ kube_file }}"
  when:
  - k3s_control_node is defined
  - k3s_control_node
