---
- name: Uninstall modemmanager
  become: true
  ansible.builtin.apt:
    name: modemmanager
    state: absent

- name: Install nfs # without this volumes wont work
  become: true
  ansible.builtin.apt:
    name: nfs-common
    update_cache: true

# Remove traefik as leveraging nginx. Adding .skip is recommended.
- name: Delete traefik file (if exists)
  become: true
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests/traefik.yaml
    state: absent
  when:
    - k3s_control_node is defined
    - k3s_control_node

- name: Create Traefik skip file
  become: true
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests/traefik.yaml.skip
    state: touch
    mode: u=rw,g=r,o=r
    modification_time: preserve
    access_time: preserve
  when:
    - k3s_control_node is defined
    - k3s_control_node

# addition to above for when running against existing install.
# 1. Run steps in https://github.com/k3s-io/k3s/issues/1160#issuecomment-1115803175
# 2. Delete left over resources - (kubectl api-resources | grep traefik) and check each resource
# 3. Delete crd - (kubectl get crd | grep traefik) THEN kubectl delete crd <crd-name>
# Another useful link: https://community.traefik.io/t/what-is-the-proper-way-to-uninstall-and-clean-up-the-traefik-helm-charts/11343

- name: Update Multipath file # https://longhorn.io/kb/troubleshooting-volume-with-multipath/
  become: true
  ansible.builtin.copy:
    src: multipath.conf
    dest: /etc/multipath.conf
    owner: root
    group: root
    mode: '0644'
    backup: true
  when: "ansible_service_mgr == 'systemd'"
  register: multipath_conf

- name: Restart multipath systemd
  become: true
  ansible.builtin.systemd:
    name: multipathd
    state: restarted
  when: multipath_conf.changed

# https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size
# Leveraged by Cloudflared
- name: Increase QUIC Buffer Size 
  become: true
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: '2500000'
    sysctl_set: true
    reload: true # default
