---
# yaml-language-server: $schema=../../../schemas/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitor-otel
  namespace: flux-system
spec:
  dependsOn:
    - name: monitor-splunk-app
#    - name: namespaces
  interval: 1h0m0s
  path: ./kubernetes/monitor/otel/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
