---
# yaml-language-server: $schema=../../../schemas/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitor-mikrotik
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-ingress-logging
  # additional inheritance from infrastructure-ingress-logging
  # - infrastructure-external-secrets-stores
  # - namespaces
  interval: 1h0m0s
  path: ./kubernetes/monitor/mikrotik/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
